/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Stock Investment Timing Dashboard API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

/**
 * Asset category
 */
export type StockDataCategory =
  (typeof StockDataCategory)[keyof typeof StockDataCategory];

export const StockDataCategory = {
  "us-stocks": "us-stocks",
  "kr-stocks": "kr-stocks",
  indices: "indices",
} as const;

/**
 * RSI signal - buy if < 30, sell if >= 70, neutral otherwise
 */
export type StockDataRsiSignal =
  (typeof StockDataRsiSignal)[keyof typeof StockDataRsiSignal];

export const StockDataRsiSignal = {
  buy: "buy",
  sell: "sell",
  neutral: "neutral",
} as const;

/**
 * MA20/MA60 cross signal detected within last 5 bars
 */
export type StockDataCrossSignal =
  (typeof StockDataCrossSignal)[keyof typeof StockDataCrossSignal];

export const StockDataCrossSignal = {
  golden: "golden",
  dead: "dead",
  none: "none",
} as const;

export interface PricePoint {
  /** Date in YYYY-MM-DD format */
  date: string;
  /** Closing price */
  close: number;
  /** MA20 at this date */
  ma20: number;
  /** MA60 at this date */
  ma60: number;
  /** Deviation from MA20 in percent */
  deviationPercent: number;
  /** Upper Bollinger Band */
  bbUpper: number;
  /** Middle Bollinger Band (SMA20) */
  bbMiddle: number;
  /** Lower Bollinger Band */
  bbLower: number;
  /** MACD line value */
  macdLine: number;
  /** MACD signal line value */
  signalLine: number;
  /** MACD histogram value */
  macdHistogram: number;
  /** True if this bar is a golden cross point (MA20 crossed above MA60) */
  isGoldenCrossPoint: boolean;
  /** True if this bar is a dead cross point (MA20 crossed below MA60) */
  isDeadCrossPoint: boolean;
}

export interface StockData {
  /** Stock ticker symbol (Yahoo Finance format) */
  symbol: string;
  /** Short display symbol for UI */
  displaySymbol: string;
  /** Full company/fund name */
  name: string;
  /** Asset category */
  category: StockDataCategory;
  /** Current stock price */
  currentPrice: number;
  /** Previous day closing price */
  previousClose: number;
  /** Price change percentage from previous close */
  changePercent: number;
  /** RSI(14) value (0-100) */
  rsi14: number;
  /** RSI signal - buy if < 30, sell if >= 70, neutral otherwise */
  rsiSignal: StockDataRsiSignal;
  /** 20-day moving average */
  ma20: number;
  /** 60-day moving average */
  ma60: number;
  /** Current price deviation from MA20 in percent */
  ma20DeviationPercent: number;
  /** Bollinger Band upper line (SMA20 + 2*stddev) */
  bbUpper: number;
  /** Bollinger Band middle line (SMA20) */
  bbMiddle: number;
  /** Bollinger Band lower line (SMA20 - 2*stddev) */
  bbLower: number;
  /** True when current price is at or below the lower Bollinger Band */
  isTouchingLowerBand: boolean;
  /** True when price touches lower BB AND RSI < 30 — extreme buy opportunity */
  isSuperBuySignal: boolean;
  /** MACD line value (EMA12 - EMA26) */
  macdLine: number;
  /** MACD signal line (EMA9 of MACD) */
  signalLine: number;
  /** MACD histogram (MACD - Signal) */
  macdHistogram: number;
  /** MA20/MA60 cross signal detected within last 5 bars */
  crossSignal: StockDataCrossSignal;
  /** True when RSI < 30 AND golden cross — best buy timing */
  isBestTiming: boolean;
  /** Historical closing prices (last 30 days with all indicators) */
  historicalPrices: PricePoint[];
  /** ISO timestamp of last update */
  lastUpdated: string;
  /** Trading volume */
  volume: number;
  /** Currency code (USD, KRW, etc.) */
  currency: string;
}

export interface StocksResponse {
  stocks: StockData[];
  /** ISO timestamp of last update */
  lastUpdated: string;
  /** List of symbols currently triggering the super buy alert */
  superBuySignals: string[];
  /** List of symbols with a recent golden cross */
  goldenCrossSignals: string[];
  /** List of symbols with a recent dead cross */
  deadCrossSignals: string[];
  /** List of symbols with RSI < 30 AND golden cross (best timing) */
  bestTimingSignals: string[];
}

export interface ErrorResponse {
  error: string;
  message: string;
}
